[package]
name = "collection"
version = "0.1.0"
authors = ["Ivan <ivan.zderadicka@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

media_info = {path="../media_info"}
sled = "0.34"
thiserror = "1.0"

[features]
partially-static = ["media_info/partially-static"]
static = ["media_info/static"]

